server:
  port: 8081
spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: nguyenvy16
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
