server:
  port: 8081

spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: postgres
    password: ${DB_PASSWORD:nguyenvy16}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET:change-this-to-a-very-long-random-secret-key-at-least-256-bits-for-hs256}
  access-token-expiration: 900000 # 15 phút (ms)
  refresh-token-expiration: 604800000 # 7 ngày (ms)
